/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PeopleCounter */

#ifndef _Included_PeopleCounter
#define _Included_PeopleCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PeopleCounter
 * Method:    detectPeople
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_modbus_PeopleCounter_detectPeople
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
